routing:
  class:                slRouter
  resolver:             slConsoleResolver
  defaultController:    Index
  controllerSuffix:     Task
  prefix:               /
  modes:                [console,web]
view:
  engine: ConsoleEngine
  format: raw